apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: content-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/G11-Engineering/g11-k8s-charts.git
    targetRevision: HEAD
    path: charts/content-service
    helm:
      releaseName: content-service
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
